package com.first.automation;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.Select;
import org.testng.annotations.Test;

public class LeaveApplication extends BaseDriver {

	@Test
	public void testLocator() throws InterruptedException {
		Driver.manage().window().maximize();
		Driver.get("https://smart-hrms.waltonbd.com/hrms/login");
		Thread.sleep(5000);
		
		
		
		WebElement userName = Driver.findElement(By.xpath("//form[1]/div[1]/div[1]/input[1]"));
		userName.sendKeys("A-17517");
		Thread.sleep(3000);
		
		WebElement password = Driver.findElement(By.xpath("//form[1]/div[2]/div[1]/div[1]/div[1]/input[1]"));
		password.sendKeys("123456");
		Thread.sleep(3000);

				WebElement element = Driver.findElement(By.id("loginButton"));
				JavascriptExecutor executor = (JavascriptExecutor)Driver;
				executor.executeScript("arguments[0].click();", element);
				Thread.sleep(5000);
		
		
				WebElement selfService = Driver.findElement(By.xpath("//body/div[1]/app-root[1]/app-all-modules[1]/app-sidebar[1]/div[1]/div[1]/perfect-scrollbar[1]/div[1]/div[1]/div[1]/ul[1]/li[6]/a[1]"));
				selfService.click();
				Thread.sleep(3000);
				
				WebElement leaveApply = Driver.findElement(By.xpath("//body/div[1]/app-root[1]/app-all-modules[1]/app-sidebar[1]/div[1]/div[1]/perfect-scrollbar[1]/div[1]/div[1]/div[1]/ul[1]/li[6]/ul[1]/li[4]/a[1]"));
				leaveApply.click();
				Thread.sleep(3000);
				
				WebElement createLeave = Driver.findElement(By.xpath("//body/div[1]/app-root[1]/app-all-modules[1]/app-self-service[1]/div[1]/app-leaves-employee[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/a[1]"));
				createLeave.click();
				Thread.sleep(5000);
				
				WebElement responsibleEmployee = Driver.findElement(By.xpath("//body/div[1]/app-root[1]/app-all-modules[1]/app-self-service[1]/div[1]/app-create-leave[1]/div[1]/div[2]/div[1]/div[1]/div[1]/form[1]/div[1]/div[3]/div[1]/ng-select[1]/div[1]/div[1]/div[2]/input[1]"));
				responsibleEmployee.sendKeys("43097");
				Thread.sleep(10000);
				
				WebElement responsibleEmployeeID = Driver.findElement(By.xpath("//span[contains(text(),'43097 - Sanjay Kumar Roy - ACTIVE')]"));
				
				int i =1;
				while(responsibleEmployeeID == null) {
					responsibleEmployee.clear();

					responsibleEmployee.sendKeys("43097");
					Thread.sleep(10000);
					i++;
						
					if(responsibleEmployeeID != null) {
						break;
					}
					if(i == 20) {
						break;
					}
				}
				
				responsibleEmployeeID.click();
				Thread.sleep(5000);
							
				WebElement leaveType = Driver.findElement(By.xpath("//body/div[1]/app-root[1]/app-all-modules[1]/app-self-service[1]/div[1]/app-create-leave[1]/div[1]/div[2]/div[1]/div[1]/div[1]/form[1]/div[1]/div[5]/div[1]/ng-select[1]/div[1]/div[1]/div[2]/input[1]"));
				leaveType.sendKeys("Medical Leave");
				Thread.sleep(3000);
				
				WebElement leaveTypeSelect = Driver.findElement(By.xpath("//span[contains(text(),'Medical Leave')]"));
				leaveTypeSelect.click();
				Thread.sleep(3000);
				
				WebElement startDate = Driver.findElement(By.xpath("//body/div[1]/app-root[1]/app-all-modules[1]/app-self-service[1]/div[1]/app-create-leave[1]/div[1]/div[2]/div[1]/div[1]/div[1]/form[1]/div[1]/div[6]/div[1]/div[1]/input[1]"));
				startDate.click();
				Thread.sleep(3000);
				
				WebElement startDateClick = Driver.findElement(By.xpath("//tbody/tr[4]/td[7]"));
				startDateClick.click();
				Thread.sleep(3000);
				
				WebElement endDate = Driver.findElement(By.xpath("//body/div[1]/app-root[1]/app-all-modules[1]/app-self-service[1]/div[1]/app-create-leave[1]/div[1]/div[2]/div[1]/div[1]/div[1]/form[1]/div[1]/div[7]/div[1]/div[1]/input[1]"));
				endDate.click();
				Thread.sleep(3000);
				
				WebElement endDateClick = Driver.findElement(By.xpath("//tbody/tr[4]/td[7]"));
				endDateClick.click();
				Thread.sleep(3000);
				
				WebElement address = Driver.findElement(By.xpath("//body/div[1]/app-root[1]/app-all-modules[1]/app-self-service[1]/div[1]/app-create-leave[1]/div[1]/div[2]/div[1]/div[1]/div[1]/form[1]/div[1]/div[9]/div[1]/textarea[1]"));
				address.sendKeys("Generated by Automation Test");
				Thread.sleep(3000);
				
				WebElement reason = Driver.findElement(By.xpath("//body/div[1]/app-root[1]/app-all-modules[1]/app-self-service[1]/div[1]/app-create-leave[1]/div[1]/div[2]/div[1]/div[1]/div[1]/form[1]/div[1]/div[10]/div[1]/textarea[1]"));
				reason.sendKeys("For Testing Purpose");
				Thread.sleep(3000);
				
				WebElement remarks = Driver.findElement(By.xpath("//body/div[1]/app-root[1]/app-all-modules[1]/app-self-service[1]/div[1]/app-create-leave[1]/div[1]/div[2]/div[1]/div[1]/div[1]/form[1]/div[1]/div[11]/div[1]/textarea[1]"));
				remarks.sendKeys("Automation Test");
				Thread.sleep(3000);
				
				
				WebElement reset = Driver.findElement(By.xpath("//body/div[1]/app-root[1]/app-all-modules[1]/app-self-service[1]/div[1]/app-create-leave[1]/div[1]/div[2]/div[1]/div[1]/div[1]/form[1]/div[2]/button[1]"));
				reset.click();
				Thread.sleep(3000);
				
				WebElement backToList = Driver.findElement(By.xpath("//body/div[1]/app-root[1]/app-all-modules[1]/app-self-service[1]/div[1]/app-create-leave[1]/div[1]/div[1]/div[1]/div[2]/a[1]"));
				backToList.click();
				Thread.sleep(3000);
				
	}

	
}

